//
//  Landmarks.swift
//  collectionViewLandmark
//
//  Created by egemen denizeri on 2.01.2022.
//

import Foundation
import UIKit

struct Landmark {
    let name: String
    let image: UIImage
    let definition: String
}
let landmarks: [Landmark] = [
    Landmark(name: "Alhambra", image: UIImage(named: "Alhambra")!, definition: "The Alhambra began as a small fortress, constructed in 889 AD by the Moors of Granada in Andalusia (Spain); then it was rebuilt and expanded by the emir Mohammed ben Al-Ahmar in the 11th Century and yet again expanded and converted into a royal palace by Sultan Yusuf I in 1333. The al-Hamra (literally, “the red one”), so named for its red clay fortress walls, was lavish – at least by European standards of the time – with all the comforts, including indoor plumbing. It integrated the natural beauty of the spot with structures and gardens designed and outfitted by the finest Muslim, Jewish, and even Christian craftsmen and artisans of the region. Among its most striking aspects, many of the interior walls and columns are inscribed in carved flowing Arabic script with poetry and verses from the Quran. The last sultan of the Nasrid dynasty, Muhammad XII, surrendered Granada to the Spanish in 1492 AD, without the Alhambra being attacked by the crusaders – otherwise it would be just another pile of rubble and memories of elegance."),
Landmark(name: "Angkor Wat", image: UIImage(named: "angkorWat")!, definition: "It has stood for nearly 1,000 years, a monument to a god and possibly the final resting place of the conqueror king who built it. And still, the temple at Angkor Wat endures, its central tower rising 213 feet above the surrounding jungle. Constructed by the Khmer King Suryavarman II in the Twelfth century in what is now northern Cambodia, it is one of the world's tallest religious monuments. A pilgrim to the city-temple of the Hindu God Vishnu would first cross a 650-foot wide and 14-feet deep moat surrounding the structure before entering a 'gopura,' a three-towered entrance leading to a raised walkway. Inside the temple complex proper, they would find four smaller towers surrounding one central 213-foot tower, evoking the sacred Mount Meru. Khmer Shaivist temples typically face east, but because Angkor Wat faces west, the final resting place for Suryavarman's remains would be a temple honoring Vishnu."),
    Landmark(name: "Chichen Itza", image: UIImage(named: "chichenItza")!, definition: "The Mayans decided to build their great city of stone in the Yucatan in the middle of a jungle instead of on some nice beach. Whatever the logic of selecting such a spot, Chichen Itza was a metropolis of homes, temples, palaces, courtyards and ballcourts of extraordinary artistry; some of the ornamented structures date back 1500 years. The ball games were a special time in the city, as the winning captain was beheaded at the end of the play as a sacrifice to the gods (seems like a perfect reason to “throw” the game), possibly at the massive stepped-pyramid Temple of Kukulcan. Chichen Itza was a thriving concern until the 13th Century, when revolt and civil war broke out among the Mayans, at which point the city went into a steep decline from which it never recovered. What war didn’t take care of among the populace, disease and famine did. The center of the city was largely abandoned and in ruins by the time of the Spanish conquest."),
Landmark(name: "Cristo Redentor", image: UIImage(named: "cristoRedentor")!,definition: "The largest art deco statue in the world, Cristo Redentor (“Christ the Redeemer”) stands atop Corcovado Mountain 2300 feet above Rio de Janeiro, keeping a watchful eye on the sinners of that city. With arms spread wide to embrace the city sprawling below in spectacular disorder, this statue of Christ stands 98 feet tall, with the arms measuring 92 feet from fingertip to fingertip. It was sculpted by the Frenchman Paul Landowski, and built of reinforced concrete and soapstone. The idea of putting a giant statue of Christ above the city was first proposed by the Catholic priest Pedro Boss; proposed again in 1920 by the “Catholic Circle” of Rio, the group raised the necessary funds from donations, mostly from devout Brazilian Catholics (of course). Construction began in 1922, and the monument opened to the public in October 1931."),
Landmark(name: "Machu Picchu", image: UIImage(named: "machuPicchu")!, definition: "At 2,430 meters above sea level in the Andes Mountains of Peru is the historic site of Machu Picchu. Once a royal estate, or perhaps a religious site, for the Incan empire, it was abandoned in the 16th century when the civilization was destroyed by a Spanish invasion. Lost to history for hundreds of years, Machu Picchu was rediscovered in 1911 by American archaeologist Hiram Bingham, exciting tourists immediately and for years to come. Today, hundreds of thousands of tourists visit the site annually. Most remarkable about the site is how seamlessly it blends into the natural world. This lost city is made up of stone terraces, a farming sector, homes, temples, and more – approximately 200 buildings in total. The finely fit stonework and intricate irrigation systems nod to the sophistication of the lost Incan civilization."),
Landmark(name: "Mont St. Michel", image: UIImage(named: "montSaintMichel")!, definition: "Perched on a rocky islet between Normandy and Brittany in the midst of sandbanks washed over by ocean tides, Mont St. Michel is a Gothic-style Benedictine abbey dedicated to the archangel Micheal built between the 11th and 16th centuries. Besides St. Aubert's skull, the Mont also was repository for bits of St. Petroc and St. Olaf and other holy relics. The place did have a practical purpose; its high walls, turrets and position made it of strategic worth … and many a French king stationed a small garrison (all that was needed) there. At low tide, it was readily accessible to pilgrims eager to give up a coin or two to be blessed; at high tide, the incoming sea would strand or drown any attacking force. The Mont would remain unconquered throughout the Hundred Years' War and beyond. Its position also made it ideal to incarcerate unrepentant traitors and other sinners; Louis XI turned the Mont into a prison, a role it served through the rest of the Ancien Régime. Now, it's still an abbey hosting a religious community, as well as a highly touristic visited place."),
Landmark(name: "Petra", image: UIImage(named: "petra")!, definition: "Situated between the Red Sea and the Dead Sea, Petra is a city cut from the red sandstone around Wadi Musa (now part of Jordan) by the Nabataeans – who obviously had a lot of free time – around 400 BC. Mentioned in Egyptian, Greek and Biblical sources, the city would develop into a major caravan center, a vital crossroads between Arabia, Egypt and Syria to the north. Surrounded by mountains riddled with gorges and canyon passages, it was defensible; but it was the ingenious and extensive system of cisterns and reservoirs in the middle of a desert that made it a trade center. At its peak, Petra was home to perhaps 20 thousand inhabitants, and served as the capital of the Nabataean kingdom. That is, until the Romans arrived and annexed it in 106 AD. Struck by a series of earthquakes, as well as Roman taxes, it was essentially abandoned two hundred years after – not to be “discovered” until 1812 by the Swiss explorer Johann Burckhardt.")]

